apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base        # <── 1. Pulls in the core files

patches:
  - path: replica-patch.yaml # <── 2. Runs the patch engine to modify the code

# Global modifiers applied to ALL resources automatically:
namePrefix: prod-     # Prepend "prod-" to all metadata names
commonLabels:
  env: production     # Injects this label into selectors and metadata blocks
